version: "3.7"

services:
  surokha_backend_app:
    build:
      dockerfile: Dockerfile
      context: ./
    image: surokha_backend_app
    container_name: surokha_backend_app
    restart: unless-stopped
    working_dir: /usr/src/app/
    volumes:
      - ./:/usr/src/app/
      - ~/datadrive/surokha-backend/application/log/:/usr/src/app/log
    env_file:
      - variables.env
    ports:
      - 9120:9120
    networks:
      - surokha_backend_net

  surokha_backend_db:
    image: mysql:5.7
    container_name: surokha_backend_db
    restart: unless-stopped
    volumes:
      - surokhabackenddbdata:/var/lib/mysql
    env_file:
      - variables.env
    ports: 
      - 3397:3306
    networks:
      - surokha_backend_net

networks:
  surokha_backend_net:
    driver: bridge

volumes:
  surokhabackenddbdata:
